### ISSUE TITLE
Add end referral section

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#10]
PEC to supply text of end referral questionnaire signposting people to other projects and benefits. @lowwwintersun to review, @Adam to add

**Comment by lowwintersun** [comment]
@AppSynergy - the list looks simple enough. 

This is a simple questionnaire with information to be collected at the end of the visit. 

It should be titled: Home Visit Checklist 

I need to clarify with them whether the responses will be displayed in the end report or just exported in to the CRM at the end. 

[SEEMs checklist carbon co-op.docx](https://github.com/carboncoop/home-energy-health-check/files/1418482/SEEMs.checklist.carbon.co-op.docx)

**Comment by AppSynergy** [comment]
Might as well add these to the same view as #17?
