### ISSUE TITLE
Details>Homeowner Details page - unique code identifier

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#11]
Add a box to fill in an unique code identifier for the assessment - protocol to be developed by PEC but likely to relate to homeowner's initials, postcode etc. Will assist with seaches.

**Comment by AppSynergy** [comment]
To check - it's the assessment that's unique, not the homeowner, right?

e.g. if one dude has two assessment, do they use the same indentifier? (no)

**Comment by lowwintersun** [comment]
Yes, and I think that would be simpler all round!
