### ISSUE TITLE
Server transfer

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#14]
Transfer tool to PEC server. 
Miles returns Monday 30 October.

**Comment by AppSynergy** [comment]
From Miles:

> Unfortunately we are only able to offer you SSH to a user directory as its a shared server environment. When you have uploaded the necessary files let me know where you want them moved to.

Do we want them moved? I don't understand what's happening here. 

---

Also, my username has a "%" character in it, that's a big problem.

````
adam%plymouthenergycommunity.com@n11:~/pechat$ git clone git@github.com:/anything
Cloning into 'anything'...
percent_expand: unknown key %p
fatal: The remote end hung up unexpectedly
````

[similar example](https://lists.mindrot.org/pipermail/openssh-unix-dev/2015-April/033824.html)

**Solution:** [listen to NAME_REGEX, don't get fancy](https://serverfault.com/questions/73084/what-characters-should-i-use-or-not-use-in-usernames-on-linux)

**Comment by lowwintersun** [comment]
To be honest, I was a bit perplexed by his email too. I think we wait for him to return on Monday - you speak to him. If it's not a go-er we need to set up a server - though the client needs to be informed that this is an additional service and we charge extra for the work and obvs they pay for the server.
