### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#15]
Jonathan to Spellcheck all sections and text!

**Comment by ghost** [comment]
Also, all references to 'Homeowner' should be changed to 'Householder' so text is tenure neutral.

**Comment by AppSynergy** [comment]
When ready here, let me know and I'll copy the fixed data from backstage4 to the new server.

**Comment by lowwintersun** [comment]
Not sure what you mean. I'm just spell-checking and amending the text on the live server.

**Comment by lowwintersun** [comment]
I've just edited the text that was there - so don't import from the test server.

**Comment by AppSynergy** [comment]
Ok great, I thought you might have already tinkered a bit with the copy on `backstage4`. I'm going to disable that one now so that no-one gets confused and edits the wrong one..

**Comment by lowwintersun** [comment]
One last thing on the test server - can you preserve it for the time being - some people want to retrieve some of the assessments in there.

**Comment by AppSynergy** [comment]
It's on again.

**Comment by lowwintersun** [comment]
Ta!
