### ISSUE TITLE
'This assessment has already been submitted.' message

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#19]
A new assessment is created. Changes are made eg measures are recommended. Clicking to the 'Done' tab, a message appears: 'This assessment has already been submitted.'

Some users report that this message leads to loss of data. 

![assessment submitted](https://user-images.githubusercontent.com/7352302/32493210-f11cbb84-c3b4-11e7-8f61-922adafea65b.png)

**Comment by AppSynergy** [comment]
DNR as far as I can see - the message will only appear if you have actually submitted the assessment (and I think loss of data should be a different issue, as I'm pretty sure it's unrelated).

The correct repro for the above:

+ A new assessment is created. 
+ Edit the assessment - changes are made eg measures are recommended. 
+ Click to the 'Done' tab, then click **Submit**.
+ Edit the attachment again.
+ Click to the 'Done' tab, a message appears: 'This assessment has already been submitted.'

Which is the intended business logic, unless I've missed something?

---

For clarity, here's what the three buttons do:

#### Save Locally

+ Save all the current assessment to localStorage (that's it)

#### Save and Quit

+ Save all the current assessment data to the database.
+ Return to the homepage.

#### Submit
+ Flip the *is_submitted* flag from 0 to 1.
+ Save all the current assessment data to the database.
+ Send an email
+ Return to the homepage.

**Comment by lowwintersun** [comment]
OK, I've so far replicated it in Firefox and Chrome on the laptop using both 'admin' and 'assessor' user accounts and after flushing the cache. 

The steps you outline above are correct, in terms of how it should work. What I'm getting is:

- A new assessment is created.
- Edit the assessment - changes are made eg measures are recommended.
- Click to the 'Done' tab, **but** before clicking Submit button the 'Already submitted...' message is already is displayed. No email has been sent and in the Admin view, the assessment is not marked as having been submitted. 
- Clicking Submit does then lead to an email being sent and the admin panel indicating that it has been Submitted. 

...as you say, this may well be unrelated to any data loss.

**Comment by AppSynergy** [comment]
You're right - got it now though! The important clue is that this only happened on the seem- domain, not any other environments.

It was a database driver issue - it wasn't using the right PDO mysql native driver and integer values were coming out as strings ("0" wasn't falsey, so the app thought you had set the submitted flag when you hadn't).

I've set the right driver now.

I don't think there's any reason to suspect this config caused any data loss, as the values are all still correct in the database itself. 

By the same logic, the "Further visit required - yes/no" field may have flipped itself to Yes in some submissions.

**Comment by lowwintersun** [comment]
Thanks Adam. I will now investigate this data loss issue further.
