### ISSUE TITLE
User access enhancement

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#2]
Different users have their own logins. An admin/owner has super-user status and assessors have ordinary user status.

**Comment by AppSynergy** [comment]
Built, will be available in release `rc-0.2`.

**Comment by lowwintersun** [comment]
Can the 'Admin' dashboard for assessors have a change password facility?

**Comment by AppSynergy** [comment]
Yes, I think so. 

They should also be able to change their own passwords with the "Forgot your password?" feature - need to get mail running for this though, and I haven't tested it yet..

**Comment by lowwintersun** [comment]
Cheers, it's low priority for now.
