### ISSUE TITLE
Submitting error

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#20]
FROM AN ASSESSOR: When I am submitting the latest assessment I have done when I hit submit on Mr Bakers, I get a red bar (as per below screen) and it won’t complete the action. It also doesn’t update on to submitted on the home screen as still showing as overdue (after refreshing screen).

![pec issue image003](https://user-images.githubusercontent.com/7352302/32609368-67abff50-c557-11e7-8b82-5cc92cd5adc2.jpg)

**Comment by AppSynergy** [comment]
What url is this screenshot taken from?

The red bar is an error alert - but it should contain the error message. It's possible the error doesn't have one. If an error is returned, the assessment is not saved.

**Comment by lowwintersun** [comment]
I think a few issues are being bundled together here. 

This assessment is one where the householder is without an email address, ie an email is not sent on clicking 'submit'.

So, the error alert may relate to that. Maybe she shouldn't 'Submit' the assessment, merely 'Save and Exit'. The delivery route is to print the PDF and mail it to the householder. A minor point here is that in the assessments list it shows as 'Overdue' because it has not been emailed. 

The assessor's more concerned about notes made in the assessment not appearing in the tables in the PDF. But I believe this is because the notes relate to measures not shown, either because they are not applicable or already in place. 

I've suggested these notes are entered in to the general, 'Assessors' Notes' at the end. 

The assessor says the red error bar is not an issue for them so I will close this issue.

**Comment by AppSynergy** [comment]
> notes made in the assessment not appearing in the tables ... the notes relate to measures not shown, either because they are not applicable or already in place.

"Not applicable" measures won't show in the tables at all, no. "I have this" shouldn't have been showing as per #3, but actually was until just now.

> the householder is without an email address, ie an email is not sent 

In which case, "Save and Quit" and "Submit" do exactly the same thing, except in the latter the "submitted" flag is set (this flag is just a feature for the user, it doesn't influence the business logic).
