### ISSUE TITLE
‘Too cold in winter’ displaying wrong

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#24]
I have just submitted an energy report and I logged the temperature as being ‘too cold in winter’ on the tool, however this is pulling through as ‘just right’ on the actual report. 

It has submitted, so there’s nothing I can do about that particular one, however if this could be rectified, it would be helpful. 

One of the other options is likely to be the ‘too cold’ one and they will just need changing around.

**Comment by AppSynergy** [comment]
Fixed.
