### ISSUE TITLE
Character limits on input fields

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#25]
Adam - can you clarify if there is any? I think you sent me some code on this but I couldn't totally understand it and the client are asking for clarification. 

Is there a way to alert assessors if they surpass the limit?

**Comment by AppSynergy** [comment]
That'll be #23, there's an SQL dump there with the details of each field.

There's two types of field of interest:

- `longtext`s where the limit is arbitrarily huge.
- `strings`, or in Mysql usually `varchar(255)` or 'varchar(191)` or similar,  where the limit is the number in brackets. 

The latter are few enough I can list them here:

`assessor_name` , `assessment_date`, `homeowner_name` , `homeowner_email`, `homeowner_phone`, `homeowner_uniqueid`, `hometype` (unused?)

I can't imagine there's many cases where the limits are exceeded, but a little validation on either the client or server side could implement an alert if necessary.

**Comment by AppSynergy** [comment]
Does this help at all, do you need any more info or any action on the above?

**Comment by lowwintersun** [comment]
Perfect - thanks!
