### ISSUE TITLE
Order of new assessments listings

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#27]
Currently new assessments are listed at the bottom of the assessments home page, but that is un-weildly as the list grows long, can newly added assessments go to the top of the list, not the bottom.

**Comment by AppSynergy** [comment]
To solve the more general case, the question is "what order should they be in"?

So perhaps `date_created`, `descending?

**Comment by AppSynergy** [comment]
Assessments are sorted as of 'rc-0.5`.
