### ISSUE TITLE
PDF page number functionality

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#28]
Can the page numbers within the PDF be numbered?

**Comment by AppSynergy** [comment]
Yes, they can. we can set e.g. a header or footer on each page of the pdf.

There's a couple of page number variables, so we can set the footer content to e.g. 

````
'Page [page] of [toPage]'
````

We can add align headers / footers center, left or right - and there's config for font size, font family, and offset from main content.

https://wkhtmltopdf.org/usage/wkhtmltopdf.txt   ( --> Headers And Footer Options: )

**Comment by lowwintersun** [comment]
Cool, let's go for:
Footer
Page [page] of [toPage]
Arial, 8pt, justified right, dark blue colour

**Comment by lowwintersun** [comment]
Black or default colour is fine
