### ISSUE TITLE
Long Recommendation titles 

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#29]
When recommendation titles are long they push the 'Something You Need', 'Something You Have' label off the right hand side of the page. 

Can we insert a <br> in to the middle of these titles?

Eg:

Recommendation 3: ‘Loft - Insulate and draughtproof an existing loft hatch’ '
‘Hot water saving - Water efficient shower head’  again, split after saving?
‘Thermostatic radiator valves TRVs (Programmable)’ split after TRVs

**Comment by AppSynergy** [comment]
Can we insert a what, a newline?

If I swap out the `text` field for a `textarea`, you should be able to then use multi-line content in Improvement titles.

**Comment by AppSynergy** [comment]
Hmm, but then it's trickier to style correctly...

how about if we allow a bit of html in the title, then you can e.g:

`Loft - Insulate and draughtproof <br>an existing loft hatch`
`‘Hot water saving<br> - Water efficient shower head`

**Comment by AppSynergy** [comment]
Better idea number two, I'll just change the markup so the title flows correctly in that part of the pdf, this means the title doesn't have to change elsewhere too. 

Available in branch `rc-0.5`.

Html titles are still available if needed...
