### ISSUE TITLE
Remove 'assessors notes' for N/A and Something You Have recommendations

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#30]
At present, assessors notes added to Recommendations marked as N/A or Something You Have do not appear in the tables - as these recommendations don't appear in the tables. 

Sometimes, assessors complete these fields in error. 

Can the notes field be removed when selecting N/A or 'Something You Have' for recommendations?

**Comment by AppSynergy** [comment]
Ok, I think this boils down to:

+ hide the notes field when 'Something You Have' or 'N/A' is selected.
+ show the notes field when 'Something You Need' is selected.

**Comment by AppSynergy** [comment]
Available in `rc-0.5`.
