### ISSUE TITLE
Emailing

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#4]
When 'submit' is selected at the end of the assessment the PDF is emailed direct to the householder. With a link to the PDF or the PDF attached and standard template email text.

**Comment by AppSynergy** [comment]
Is working:

![ok](https://i.imgur.com/GIsD6bQ.png)

I don't want to hijack my own mailserver right now, so it currently goes to a free mailtrap.io account.

When we get onto the right server, we can setup SMTP there.

**Comment by lowwintersun** [comment]
Amazing, looks great! Closed pending SMTP?
