### ISSUE TITLE
Remove & Add elements of the Comfort and Health questionnaire

### ISSUE THREAD

**Issue by lowwintersun** [carboncoop/home-energy-health-check#8]
@marianneURBED to confirm questions to be removed/added*, Adam to remove/add.

* I think the only addition was light bulbs.

**Comment by ghost** [comment]
Hi, 

See attached illustrations for changes to comfort and health questionnaire. Hopefully self-explanatory, but let me know if not. (Lightbulbs is a separate issue I think - will have a look now). 

Thanks, 

Marianne 
[20171030143925.pdf](https://github.com/carboncoop/home-energy-health-check/files/1427539/20171030143925.pdf)

**Comment by AppSynergy** [comment]
No worries, think I've got it.

One thing to clarify - those marked **omit**, should I completely remove them from the data model as well as the form? These definitely won't be needed again?

**Comment by ghost** [comment]
If you can without too much trouble, just omit them from the form for now. 

There's a small chance that if PEC get more measuring kit, or after they've done a lot and/or the focus shifts for them, they might want them again in the future (though also I think they're less relevant generally, so good chance will never happen).

Thanks
